name: Update cache
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-cache:
    name: Update Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: create env file
        run: |
          touch .env
          echo "API_URL=${{ secrets.API_URL }}" > .env
          echo "API_KEY=${{secrets.API_KEY}}" >> .env
          echo "WAKAPI_URL=${{secrets.WAKAPI_URL}}" >> .env
      - run: bun install
      - run: bun run do-cache.ts
